language: c
# Script will setup ccs and build
script: ./build.sh
install:
  - ./travis-setup.sh
before_install:
  - ./dependencies.sh
notifications:
  email:
    - chris@sayhello.com
deploy:
  provider: s3
  access_key_id: AKIAIJE3P5YMHYZQDY4Q
  secret_access_key: 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
  bucket: "hello-firmware"
  upload-dir: sense/releases
  file: kitsune/main/ccs/exe/kitsune.bin
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

